export const AllBuildingAmenities = [
  {
    id: 0,
    name: 'Swimming Pool',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 1,
    name: 'Fitness Center',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 2,
    name: 'Parking Garage',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 3,
    name: 'Elevator',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 4,
    name: 'Security System',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 5,
    name: 'Concierge Service',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 6,
    name: 'Roof Terrace',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 7,
    name: 'Business Center',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 8,
    name: 'Laundry Facilities',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 9,
    name: 'Pet-Friendly',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 10,
    name: 'Bicycle Storage',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8],
  },
  {
    id: 11,
    name: '24/7 Security',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 12,
    name: 'On-Site Maintenance',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 13,
    name: 'On-Site Management',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 14,
    name: 'Lounge Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 15,
    name: 'Outdoor BBQ Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 16,
    name: 'Playground',
    checked: false,
    flatType: [1, 2, 3, 6, 13],
  },
  {
    id: 17,
    name: 'Tennis Court',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 18,
    name: 'Basketball Court',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 19,
    name: 'Movie Theater',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 20,
    name: 'Party Room',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 21,
    name: 'Yoga Studio',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 22,
    name: 'Dog Park',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 23,
    name: 'Gymnasium',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 24,
    name: 'Library',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 25,
    name: 'Sauna',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 26,
    name: 'Jacuzzi',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 27,
    name: 'BBQ/Picnic Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 28,
    name: 'Courtyard',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 29,
    name: 'Gated Community',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 30,
    name: 'Car Parking',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 31,
    name: 'Car Wash Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 32,
    name: 'Electric Vehicle Charging',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 33,
    name: 'Child Care Center',
    checked: false,
    flatType: [1, 2, 3, 6, 7, 8, 13, 14],
  },
  {
    id: 34,
    name: 'Cafeteria',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 35,
    name: 'Roof Garden',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 36,
    name: 'Dog Wash Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 37,
    name: 'On-Site Grocery Store',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 38,
    name: 'Rooftop Pool',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 39,
    name: 'Bike Repair Station',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 40,
    name: 'Pet Washing Station',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 41,
    name: 'Indoor Pool',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 42,
    name: 'Garden View',
    checked: false,
    flatType: [6, 9, 10, 11, 12],
  },
  {
    id: 43,
    name: 'Balcony',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 44,
    name: 'Fireplace',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 45,
    name: 'Central Heating',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 46,
    name: 'Air Conditioning',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 47,
    name: 'High-Speed Internet',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 48,
    name: 'Cable/Satellite TV',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 49,
    name: 'Washer/Dryer in Unit',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 50,
    name: 'Dishwasher',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 51,
    name: 'Garbage Disposal',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 52,
    name: 'Walk-in Closet',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 53,
    name: 'Hardwood Floors',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 54,
    name: 'Carpet',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 55,
    name: 'Tile Floors',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 56,
    name: 'Vaulted Ceilings',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 57,
    name: 'Patio',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 58,
    name: 'Furnished',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 59,
    name: 'Wheelchair Accessible',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 12],
  },
  {
    id: 60,
    name: 'On-Site Security',
    checked: false,
    flatType: [4, 8],
  },

  {
    id: 61,
    name: 'Fitness Classes',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 62,
    name: 'Golf Course',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 63,
    name: 'Rooftop Lounge',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 64,
    name: 'Game Room',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 65,
    name: 'Conference Room',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 66,
    name: 'Guest Suites',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 67,
    name: 'Package Service',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 68,
    name: 'Dog-Friendly Park',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 69,
    name: 'Bike Sharing',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 70,
    name: 'Basketball Court',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 71,
    name: 'Volleyball Court',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 72,
    name: 'BBQ/Picnic Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 73,
    name: 'Community Garden',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 74,
    name: 'Billiards',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 75,
    name: 'Virtual Concierge',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 76,
    name: 'Tanning Beds',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 77,
    name: 'Electric Car Charging',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 78,
    name: 'Outdoor Fireplace',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 79,
    name: 'On-Site Pharmacy',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 80,
    name: 'Dog Walking Services',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 81,
    name: 'Art Studio',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 82,
    name: 'Hiking Trails',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 83,
    name: 'Indoor Pool',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 84,
    name: 'Yoga Terrace',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 85,
    name: 'Cinema Room',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 86,
    name: 'Music Room',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 87,
    name: 'Dog Agility Park',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 88,
    name: 'Racquetball Court',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 89,
    name: 'Sky Lounge',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 90,
    name: 'Outdoor Fitness Area',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 91,
    name: 'Barbecue Pavilion',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 92,
    name: 'Community Kitchen',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 93,
    name: 'Pet Spa',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 94,
    name: 'Zen Garden',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 95,
    name: 'Rooftop Farm',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 96,
    name: 'Conference Center',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 97,
    name: 'Dog Run',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 98,
    name: 'Wine Cellar',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 99,
    name: 'Skyline View',
    checked: false,
    flatType: [4, 8],
  },
  {
    id: 100,
    name: 'Zen Room',
    checked: false,
    flatType: [4, 8],
  },
];
