export const countries = [
  {
    id: 1,
    name: 'Jordan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 2,
    name: 'Northern Mariana Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 3,
    name: 'Serbia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 4,
    name: 'Andorra',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 5,
    name: 'Turks and Caicos Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 6,
    name: 'Bermuda',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 7,
    name: 'Antarctica',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 8,
    name: 'Bolivia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 9,
    name: 'Libya',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 10,
    name: 'Mali',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 11,
    name: 'Armenia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 12,
    name: 'Mauritius',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 13,
    name: 'Maldives',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 14,
    name: 'American Samoa',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 15,
    name: 'North Macedonia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 16,
    name: 'Ethiopia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 17,
    name: 'Greenland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 18,
    name: 'Iraq',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 19,
    name: 'Guatemala',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 20,
    name: 'Trinidad and Tobago',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 21,
    name: 'Peru',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 22,
    name: 'Suriname',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 23,
    name: 'Sweden',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 24,
    name: 'New Caledonia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 25,
    name: 'French Polynesia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 26,
    name: 'Benin',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 27,
    name: 'Estonia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 28,
    name: 'Falkland Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 29,
    name: 'Guam',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 30,
    name: 'Zimbabwe',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 31,
    name: 'Slovakia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 32,
    name: 'Netherlands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 33,
    name: 'Ecuador',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 34,
    name: 'Saudi Arabia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 35,
    name: 'United Arab Emirates',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 36,
    name: 'Afghanistan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 37,
    name: 'United States Minor Outlying Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 38,
    name: 'Central African Republic',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 39,
    name: 'Panama',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 40,
    name: 'Vatican City',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 41,
    name: 'Syria',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 42,
    name: 'Vanuatu',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 43,
    name: 'Honduras',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 44,
    name: 'Kiribati',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 45,
    name: 'Chile',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 46,
    name: 'Burkina Faso',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 47,
    name: 'Saint Kitts and Nevis',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 48,
    name: 'Saint Barth\u00e9lemy',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 49,
    name: 'Mexico',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 50,
    name: 'China',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 51,
    name: 'Timor-Leste',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 52,
    name: 'British Indian Ocean Territory',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 53,
    name: 'South Sudan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 54,
    name: 'Eswatini',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 55,
    name: 'Uzbekistan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 56,
    name: 'Indonesia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 57,
    name: 'Paraguay',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 58,
    name: 'Monaco',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 59,
    name: 'Grenada',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 60,
    name: 'Croatia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 61,
    name: 'Poland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 62,
    name: 'Bosnia and Herzegovina',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 63,
    name: 'Canada',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 64,
    name: 'Portugal',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 65,
    name: 'Brazil',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 66,
    name: 'Mauritania',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 67,
    name: 'Israel',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 68,
    name: 'Cura\u00e7ao',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 69,
    name: 'Brunei',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 70,
    name: 'Angola',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 71,
    name: 'Malta',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 72,
    name: 'Belarus',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 73,
    name: 'Turkey',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 74,
    name: 'Finland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 75,
    name: 'Gibraltar',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 76,
    name: 'Bhutan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 77,
    name: 'Spain',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 78,
    name: 'Venezuela',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 79,
    name: 'Qatar',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 80,
    name: 'Czechia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 81,
    name: 'Kuwait',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 82,
    name: 'Montenegro',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 83,
    name: 'Bouvet Island',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 84,
    name: 'India',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 85,
    name: 'New Zealand',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 86,
    name: 'Jamaica',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 87,
    name: 'Cayman Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 88,
    name: 'San Marino',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 89,
    name: 'Republic of the Congo',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 90,
    name: 'Pakistan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 91,
    name: 'France',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 92,
    name: 'Kazakhstan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 93,
    name: 'Bahrain',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 94,
    name: 'Fiji',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 95,
    name: 'Iceland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 96,
    name: 'Myanmar',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 97,
    name: 'Bangladesh',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 98,
    name: 'Philippines',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 99,
    name: 'Equatorial Guinea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 100,
    name: 'Ireland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 101,
    name: 'Nepal',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 102,
    name: 'Yemen',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 103,
    name: 'South Korea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 104,
    name: 'Denmark',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 105,
    name: 'Oman',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 106,
    name: 'Saint Vincent and the Grenadines',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 107,
    name: 'Eritrea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 108,
    name: 'Australia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 109,
    name: 'Iran',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 110,
    name: 'El Salvador',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 111,
    name: 'Tanzania',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 112,
    name: 'Guadeloupe',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 113,
    name: 'Solomon Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 114,
    name: 'Kenya',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 115,
    name: 'Dominican Republic',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 116,
    name: 'Greece',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 117,
    name: 'Guernsey',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 118,
    name: 'Rwanda',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 119,
    name: 'Saint Pierre and Miquelon',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 120,
    name: 'Tuvalu',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 121,
    name: 'Taiwan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 122,
    name: 'Guyana',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 123,
    name: 'Seychelles',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 124,
    name: 'North Korea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 125,
    name: 'Botswana',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 126,
    name: 'Cambodia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 127,
    name: 'Barbados',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 128,
    name: 'Colombia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 129,
    name: 'Ukraine',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 130,
    name: 'Ivory Coast',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 131,
    name: 'Nauru',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 132,
    name: 'Namibia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 133,
    name: 'Chad',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 134,
    name: 'Tonga',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 135,
    name: 'Argentina',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 136,
    name: 'Christmas Island',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 137,
    name: 'Niger',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 138,
    name: 'Marshall Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 139,
    name: 'Costa Rica',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 140,
    name: 'Ghana',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 141,
    name: 'Austria',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 142,
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 143,
    name: 'Palestine',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 144,
    name: 'Cuba',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 145,
    name: 'Hungary',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 146,
    name: 'Micronesia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 147,
    name: 'Belize',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 148,
    name: 'Bahamas',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 149,
    name: 'Aruba',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 150,
    name: 'S\u00e3o Tom\u00e9 and Pr\u00edncipe',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 151,
    name: 'Russia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 152,
    name: 'Luxembourg',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 153,
    name: 'Faroe Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 154,
    name: 'Nicaragua',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 155,
    name: 'Tunisia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 156,
    name: 'DR Congo',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 157,
    name: 'Svalbard and Jan Mayen',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 158,
    name: 'South Africa',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 159,
    name: 'Sierra Leone',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 160,
    name: 'Lesotho',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 161,
    name: 'South Georgia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 162,
    name: 'Italy',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 163,
    name: 'Djibouti',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 164,
    name: 'Heard Island and McDonald Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 165,
    name: 'Sri Lanka',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 166,
    name: 'Saint Lucia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 167,
    name: 'Samoa',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 168,
    name: 'Cocos (Keeling) Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 169,
    name: 'Puerto Rico',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 170,
    name: 'Gabon',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 171,
    name: 'Turkmenistan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 172,
    name: 'Latvia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 173,
    name: 'Senegal',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 174,
    name: 'Belgium',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 175,
    name: 'Moldova',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 176,
    name: 'Liechtenstein',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 177,
    name: 'Malawi',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 178,
    name: 'Lebanon',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 179,
    name: 'Mongolia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 180,
    name: 'Norway',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 181,
    name: 'British Virgin Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 182,
    name: 'Cameroon',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 183,
    name: 'Thailand',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 184,
    name: 'Nigeria',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 185,
    name: 'R\u00e9union',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 186,
    name: 'Cape Verde',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 187,
    name: 'Jersey',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 188,
    name: 'Algeria',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 189,
    name: 'Laos',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 190,
    name: 'Caribbean Netherlands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 191,
    name: 'Azerbaijan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 192,
    name: 'Sint Maarten',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 193,
    name: 'Morocco',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 194,
    name: '\u00c5land Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 195,
    name: 'Bulgaria',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 196,
    name: 'Burundi',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 197,
    name: 'Uganda',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 198,
    name: 'Kosovo',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 199,
    name: 'Mozambique',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 200,
    name: 'Georgia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 201,
    name: 'United Kingdom',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 202,
    name: 'Wallis and Futuna',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 203,
    name: 'Pitcairn Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 204,
    name: 'Romania',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 205,
    name: 'Vietnam',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 206,
    name: 'French Southern and Antarctic Lands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 207,
    name: 'Western Sahara',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 208,
    name: 'Japan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 209,
    name: 'Egypt',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 210,
    name: 'Liberia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 211,
    name: 'Lithuania',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 212,
    name: 'Haiti',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 213,
    name: 'United States Virgin Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 214,
    name: 'Papua New Guinea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 215,
    name: 'Hong Kong',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 216,
    name: 'Kyrgyzstan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 217,
    name: 'Palau',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 218,
    name: 'Madagascar',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 219,
    name: 'Gambia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 220,
    name: 'Togo',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 221,
    name: 'Tokelau',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 222,
    name: 'Slovenia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 223,
    name: 'Singapore',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 224,
    name: 'French Guiana',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 225,
    name: 'United States',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 226,
    name: 'Montserrat',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 227,
    name: 'Malaysia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 228,
    name: 'Germany',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 229,
    name: 'Antigua and Barbuda',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 230,
    name: 'Saint Martin',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 231,
    name: 'Somalia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 232,
    name: 'Macau',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 233,
    name: 'Albania',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 234,
    name: 'Mayotte',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 235,
    name: 'Dominica',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 236,
    name: 'Zambia',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 237,
    name: 'Anguilla',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 238,
    name: 'Cook Islands',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 239,
    name: 'Martinique',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 240,
    name: 'Guinea',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 241,
    name: 'Comoros',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 242,
    name: 'Niue',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 243,
    name: 'Switzerland',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 244,
    name: 'Norfolk Island',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 245,
    name: 'Isle of Man',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 246,
    name: 'Sudan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 247,
    name: 'Tajikistan',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 248,
    name: 'Uruguay',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 249,
    name: 'Cyprus',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
  {
    id: 250,
    name: 'Guinea-Bissau',
    currency: null,
    currencyCode: 'AFN',
    currencySymbol: '&#1547;',
  },
];
