export const AllFlatTypes = [
  {
    id: 1,
    label: '1 BHK',
    checked: false,
    src: '',
    features: ['1 Bedroom', '1 Hall Room', '1 Kitchen and Bathroom'],
  },
  {
    id: 2,
    label: '2 BHK',
    checked: false,
    src: '',
    features: ['2 Bedroom', 'A Hall Room', ' Kitchen and Bathroom'],
  },
  {
    id: 3,
    label: '3 BHK',
    checked: false,
    src: '',
    features: ['3 Bedroom', 'A Hall Room', ' Kitchen and Bathroom'],
  },
  {
    id: 4,
    label: 'Penthouse',
    checked: false,
    src: '',
    features: [
      'Toop Floor Of Building',
      'Luxurious Design and Finishes',
      ' Private Outdoor Space',
    ],
  },
  {
    id: 5,
    label: 'Duplex',
    checked: false,
    src: '',
    features: ['Two-Story Layout', 'Internal Staircase', ' Separate Entrances'],
  },
  {
    id: 6,
    label: 'Garden Apartment',
    checked: false,
    src: '',
    features: ['Ground Floor Location', 'Access to a Garden'],
  },
  {
    id: 7,
    label: 'Serviced Apartment',
    checked: false,
    src: '',
    features: [
      'Furnished Apartments',
      'Hotel-like Services',
      'Flexible Rental Options',
    ],
  },
  {
    id: 8,
    label: 'Luxury Apartment',
    checked: false,
    src: '',
    features: [
      'High-End Finishes and Features',
      'Extensive Amenities',
      'Prime Location and Views',
    ],
  },
  {
    id: 9,
    label: 'Micro Apartment',
    checked: false,
    src: '',
    features: [
      'Small Size',
      'Multifunctional Design',
      'Efficient Use of Space',
    ],
  },
  {
    id: 10,
    label: 'Office Space',
    checked: false,
    src: '',
    features: [
      'Prime Location',
      'Infrastructure and Services',
      'Work Environment',
    ],
  },
  {
    id: 11,
    label: 'Basement Apartment',
    checked: false,
    src: '',
    features: ['Below ground floor', 'Seperate entrance'],
  },
  {
    id: 12,
    label: 'Studio Apartment',
    checked: false,
    src: '',
    features: ['Open layout', 'Compact size', 'Combined functions'],
  },
  {
    id: 13,
    label: 'Student Housing',
    checked: false,
    src: '',
    features: [
      'Shared Living Spaces',
      'Amenities and Support Services',
      'Proximity to Campus',
    ],
  },
  {
    id: 14,
    label: 'Shared Apartment',
    checked: false,
    src: '',
    features: [
      'Shared Living Space',
      'Splitting of Expenses',
      'Shared Responsibilities',
    ],
  },
];
