export const flatFees = [
  {
    id: 1,
    name: 'Purchase Cost',
    checked: false,
    formName: 'purchaseCost',
    purpose: ['sell'],
  },
  // {
  //   id: 2,
  //   name: 'Rental Cost',
  //   checked: false,
  //   formName: 'rentCost',
  //   purpose: ['rent'],
  // },
  // {
  //   id: 3,
  //   name: 'Monthly Cost',
  //   checked: false,
  //   formName: 'monthlyCost',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 4,
  //   name: 'Yearly Cost',
  //   checked: false,
  //   formName: 'yearlyCost',
  //   purpose: ['rent', 'sell'],
  // },

  // {
  //   id: 5,
  //   name: 'Insurance Cost',
  //   checked: false,
  //   formName: 'insuranceCost',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 6,
  //   name: 'Property Tax',
  //   checked: false,
  //   formName: 'propertyTax',
  //   purpose: ['sell'],
  // },
  // {
  //   id: 7,
  //   name: 'Internet Cost',
  //   checked: false,
  //   formName: 'internetCost',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 8,
  //   name: 'Parking Fee',
  //   checked: false,
  //   formName: 'parkingFee',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 9,
  //   name: 'Pet Fee',
  //   checked: false,
  //   formName: 'petFee',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 10,
  //   name: 'Communal Facility Fee',
  //   checked: false,
  //   formName: 'communalFacilityFee',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 11,
  //   name: 'Cleaning Fee',
  //   checked: false,
  //   formName: 'cleaningFee',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 12,
  //   name: 'Home Improvement/Upgrades',
  //   checked: false,
  //   formName: 'homeImprovement',
  //   purpose: ['sell'],
  // },
  // {
  //   id: 13,
  //   name: 'Furniture and Appliances',
  //   checked: false,
  //   formName: 'furnitureAppliances',
  //   purpose: ['sell'],
  // },
  // {
  //   id: 14,
  //   name: 'Legal and Administrative Fees',
  //   checked: false,
  //   formName: 'legalFees',
  //   purpose: ['sell'],
  // },
  // {
  //   id: 15,
  //   name: 'Moving Costs',
  //   checked: false,
  //   formName: 'movingCosts',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 16,
  //   name: 'Security System',
  //   checked: false,
  //   formName: 'securitySystem',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 17,
  //   name: 'Home Office Setup',
  //   checked: false,
  //   formName: 'homeOfficeSetup',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 18,
  //   name: 'Cleaning and Pest Control',
  //   checked: false,
  //   formName: 'cleaningPestControl',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 19,
  //   name: 'Renewal Fees',
  //   checked: false,
  //   formName: 'renewalFees',
  //   purpose: ['rent'],
  // },
  // {
  //   id: 20,
  //   name: 'Maintenance and Repairs',
  //   checked: false,
  //   formName: 'maintenanceRepairs',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 21,
  //   name: 'Mortgage Payments',
  //   checked: false,
  //   formName: 'mortgagePayments',
  //   purpose: ['sell'],
  // },
  // {
  //   id: 22,
  //   name: 'Utilities',
  //   checked: false,
  //   formName: 'utilityCost',
  //   purpose: ['rent', 'sell'],
  // },
  // {
  //   id: 23,
  //   name: 'Other Costs',
  //   checked: false,
  //   formName: 'otherCost',
  //   purpose: ['rent', 'sell'],
  // },
];
