export const AllFlatAmenities = [
  {
    id: 1,
    name: 'Air Conditioning',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 2,
    name: 'Heating',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 3,
    name: 'Balcony/Patio',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 4,
    name: 'Furnished',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 5,
    name: 'Dishwasher',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 6,
    name: 'Refrigerator',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 7,
    name: 'Washer/Dryer',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 8,
    name: 'Walk-in Closet',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 9,
    name: 'Hardwood Floors',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 10,
    name: 'Carpet',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 11,
    name: 'Tile Floors',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 12,
    name: 'Cable/Satellite TV',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 13,
    name: 'High-Speed Internet',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 14,
    name: 'Smoke-Free',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 15,
    name: 'Microwave',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 16,
    name: 'Oven',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 17,
    name: 'Stove',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 18,
    name: 'Garbage Disposal',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 19,
    name: 'Ceiling Fan',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 20,
    name: 'Fireplace',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 21,
    name: 'Pet-Friendly',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 22,
    name: 'Wheelchair Accessible',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 23,
    name: 'Alarm System',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 24,
    name: 'Garage',
    checked: false,
    flatType: [1, 2, 3, 4, 6, 7, 8, 13, 14],
  },
  {
    id: 25,
    name: 'Storage Space',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },

  {
    id: 26,
    name: 'Swimming Pool',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 27,
    name: 'Fitness Center',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 28,
    name: 'Laundry Facility',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 29,
    name: 'On-Site Maintenance',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 30,
    name: 'Gated Community',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 31,
    name: 'Covered Parking',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 32,
    name: 'Elevator',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 33,
    name: 'Security System',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 34,
    name: 'Yard',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 35,
    name: 'Deck/Patio',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 36,
    name: 'Private Entrance',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 37,
    name: 'Off-Street Parking',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 38,
    name: 'Community Room',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 39,
    name: 'Business Center',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 40,
    name: 'Basketball Court',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 41,
    name: 'Fireplace',
    checked: false,
    flatType: [4, 7, 8],
  },

  {
    id: 43,
    name: 'Tennis Court',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 44,
    name: 'Playground',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 45,
    name: 'Bike Storage',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 46,
    name: 'Roof Deck',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 47,
    name: 'Gym',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 48,
    name: 'Hot Tub',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
  {
    id: 49,
    name: 'BBQ Area',
    checked: false,
    flatType: [4, 7, 8],
  },
  {
    id: 50,
    name: 'On-Site Management',
    checked: false,
    flatType: [1, 2, 3, 4, 7, 8, 13, 14],
  },
];
